import { importProvidersFrom } from '@angular/core';
import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { 
  LucideAngularModule, 
  Plus, 
  Search, 
  Calendar, 
  Check, 
  CircleAlert, 
  TriangleAlert, 
  Eye, 
  X, 
  ChevronRight,
  FileText,
  History,
  Info,
  Package,
  Truck,
  Activity,
  Clock,
  ArrowDownUp,
  ShieldCheck,
  LayoutDashboard,
  Box,
  ClipboardList,
  RefreshCw,
  ShoppingCart,
  Settings,
  LogOut,
  User,
  Bell,
  Wrench,
  PlusCircle,
  ArrowRightLeft,
  RotateCcw,
  MessageCircle,
  Star,
  ClipboardCheck,
  List,
  Wind,
  ChevronDown,
  LayoutGrid,
  ArrowLeft,
  Trash2,
  Minus,
  CircleHelp,
  Circle
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor, errorInterceptor])),
    importProvidersFrom(LucideAngularModule.pick({ 
      Plus, 
      Search, 
      Calendar, 
      Check, 
      CircleAlert, 
      TriangleAlert, 
      Eye, 
      X, 
      ChevronRight,
      FileText,
      History,
      Info,
      Package,
      Truck,
      Activity,
      Clock,
      ArrowDownUp,
      ShieldCheck,
      LayoutDashboard,
      Box,
      ClipboardList,
      RefreshCw,
      ShoppingCart,
      Settings,
      LogOut,
      User,
      Bell,
      Wrench,
      PlusCircle,
      ArrowRightLeft,
      RotateCcw,
      MessageCircle,
      Star,
      ClipboardCheck,
      List,
      Wind,
      ChevronDown,
      LayoutGrid,
      ArrowLeft,
      Trash2,
      Minus,
      CircleHelp,
      Circle
    }))
  ],
};
