import { NgModule } from '@angular/core';
import {
  Activity,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpNarrowWide,
  BarChart3,
  Bell,
  Box,
  Calendar,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  DollarSign,
  Download,
  Edit,
  Eye,
  FileText,
  History,
  Info,
  LayoutDashboard,
  LayoutGrid,
  List,
  LogOut,
  LucideAngularModule,
  MessageCircle,
  Minus,
  Package,
  Plus,
  RotateCcw,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TicketPlus,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  Truck,
  UserRoundX,
  Wrench,
  X,
} from 'lucide-angular';

export const PORTAL_ICONS = {
  Activity,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpNarrowWide,
  BarChart3,
  Bell,
  Box,
  Calendar,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  DollarSign,
  Download,
  Edit,
  Eye,
  FileText,
  History,
  Info,
  LayoutDashboard,
  LayoutGrid,
  List,
  LogOut,
  MessageCircle,
  Minus,
  Package,
  Plus,
  RotateCcw,
  Search,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TicketPlus,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  Truck,
  UserRoundX,
  Wrench,
  X,
};

export const PORTAL_ICON_NAMES = [
  'activity', 'arrow-down-wide-narrow', 'arrow-left', 'arrow-right-left', 'arrow-up-narrow-wide',
  'bar-chart-3', 'bell', 'box', 'calendar', 'chart-no-axes-column', 'check', 'chevron-down',
  'chevron-right', 'circle', 'circle-alert', 'circle-check-big', 'clipboard-check', 'clipboard-list',
  'dollar-sign', 'download', 'edit', 'eye', 'file-text', 'history', 'info', 'layout-dashboard',
  'layout-grid', 'list', 'log-out', 'message-circle', 'minus', 'package', 'plus', 'rotate-ccw',
  'search', 'shield-check', 'shopping-bag', 'shopping-cart', 'sliders-horizontal', 'star',
  'ticket-plus', 'timer', 'timer-off', 'trash-2', 'triangle-alert', 'truck', 'user-round-x',
  'wrench', 'x',
] as const;

@NgModule({
  imports: [LucideAngularModule.pick(PORTAL_ICONS)],
  exports: [LucideAngularModule],
})
export class PortalIconsModule {}
