import { NgModule } from '@angular/core';
import {
  Activity,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpNarrowWide,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Calendar,
  Camera,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  History,
  House,
  Image,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  MessageCircle,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  Paperclip,
  Phone,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TicketPlus,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  Truck,
  User,
  UserCheck,
  UserPlus,
  UserRoundX,
  UserX,
  Users,
  Wrench,
  X,
} from 'lucide-angular';

export const PORTAL_ICONS = {
  Activity,
  ArrowDownWideNarrow,
  ArrowLeft,
  ArrowRightLeft,
  ArrowUpNarrowWide,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Calendar,
  Camera,
  ChartNoAxesColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleCheckBig,
  ClipboardCheck,
  ClipboardList,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  History,
  House,
  Image,
  Info,
  Landmark,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  List,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Minus,
  MoreHorizontal,
  MoreVertical,
  Package,
  Paperclip,
  Phone,
  Plus,
  Printer,
  RefreshCw,
  RotateCcw,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  TicketPlus,
  Timer,
  TimerOff,
  Trash2,
  TriangleAlert,
  Truck,
  User,
  UserCheck,
  UserPlus,
  UserRoundX,
  UserX,
  Users,
  Wrench,
  X,
};

export const PORTAL_ICON_NAMES = [
  'activity', 'arrow-down-wide-narrow', 'arrow-left', 'arrow-right-left', 'arrow-up-narrow-wide',
  'bar-chart-3', 'bell', 'book-open', 'box', 'calendar', 'camera', 'chart-no-axes-column', 'check', 'chevron-down',
  'chevron-left', 'chevron-right', 'circle', 'circle-alert', 'circle-check-big', 'clipboard-check', 'clipboard-list',
  'clock', 'credit-card', 'dollar-sign', 'download', 'edit', 'external-link', 'eye', 'eye-off', 'file-text', 'filter',
  'history', 'house', 'image', 'info', 'landmark', 'layers', 'layout-dashboard',
  'layout-grid', 'list', 'lock', 'log-out', 'mail', 'map-pin', 'message-circle', 'minus', 'more-horizontal', 'more-vertical',
  'package', 'paperclip', 'plus', 'printer',
  'refresh-cw', 'rotate-ccw', 'search', 'send', 'settings', 'shield', 'shield-check', 'shopping-bag',
  'shopping-cart', 'sliders-horizontal', 'star', 'ticket-plus', 'timer', 'timer-off', 'trash-2',
  'triangle-alert', 'truck', 'user', 'user-check', 'user-plus', 'user-round-x', 'user-x', 'users',
  'wrench', 'x',
] as const;

@NgModule({
  imports: [LucideAngularModule.pick(PORTAL_ICONS)],
  exports: [LucideAngularModule],
})
export class PortalIconsModule {}
